/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdvancedSettings
 */
export interface AdvancedSettings {
    /**
     * Whether to preload the LLM with a dummy prompt on startup to reduce first-run latency
     * @type {boolean}
     * @memberof AdvancedSettings
     */
    'warmUpOnLaunch'?: boolean;
    /**
     * Enable verbose logging for troubleshooting
     * @type {boolean}
     * @memberof AdvancedSettings
     */
    'debugLogging'?: boolean;
}

