/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Behaviors
 */
export interface Behaviors {
    /**
     * Global setting to enable/disable copying results to clipboard
     * @type {boolean}
     * @memberof Behaviors
     */
    'clipboard'?: boolean;
    /**
     * Global setting to enable/disable automatic pasting of results at cursor position
     * @type {boolean}
     * @memberof Behaviors
     */
    'autoPaste'?: boolean;
    /**
     * Delay in milliseconds before auto-pasting, useful for slow or complex editors
     * @type {number}
     * @memberof Behaviors
     */
    'pasteDelayMs'?: number;
}

