/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LLMInfo
 */
export interface LLMInfo {
    /**
     * Name and version of the loaded language model
     * @type {string}
     * @memberof LLMInfo
     */
    'model': string;
    /**
     * Whether the LLM is successfully loaded and ready for inference
     * @type {boolean}
     * @memberof LLMInfo
     */
    'loaded': boolean;
}

