/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Mode = {
    Append: 'append',
    Replace: 'replace'
} as const;

export type Mode = typeof Mode[keyof typeof Mode];



