/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RewriteResponse
 */
export interface RewriteResponse {
    /**
     * The processed text output from the LLM after applying the prompt to the input
     * @type {string}
     * @memberof RewriteResponse
     */
    'result': string;
}

