/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdvancedSettings } from './advanced-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Behaviors } from './behaviors';

/**
 * Same fields as SettingsRequest for GET and POST.
 * @export
 * @interface SettingsResponse
 */
export interface SettingsResponse {
    /**
     * Mapping of trigger names to their corresponding prompt templates
     * @type {{ [key: string]: string; }}
     * @memberof SettingsResponse
     */
    'prompts': { [key: string]: string; };
    /**
     * Default insertion modes for each trigger or globally
     * @type {{ [key: string]: string; }}
     * @memberof SettingsResponse
     */
    'modes': { [key: string]: string; };
    /**
     * Global clipboard and auto-paste behavior settings
     * @type {Behaviors}
     * @memberof SettingsResponse
     */
    'behaviors': Behaviors;
    /**
     * Advanced configuration options including model warm-up and logging
     * @type {AdvancedSettings}
     * @memberof SettingsResponse
     */
    'advanced': AdvancedSettings;
}

export const SettingsResponseModesEnum = {
    Append: 'append',
    Replace: 'replace'
} as const;

export type SettingsResponseModesEnum = typeof SettingsResponseModesEnum[keyof typeof SettingsResponseModesEnum];


