/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LLMInfo } from './llminfo';
// May contain unused imports in some cases
// @ts-ignore
import type { STTInfo } from './sttinfo';

/**
 * 
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
    /**
     * Status information about the language model
     * @type {LLMInfo}
     * @memberof StatusResponse
     */
    'llm': LLMInfo;
    /**
     * Status information about the speech-to-text engine
     * @type {STTInfo}
     * @memberof StatusResponse
     */
    'stt': STTInfo;
    /**
     * Currently configured submission hotkey combination
     * @type {string}
     * @memberof StatusResponse
     */
    'hotkey': string;
    /**
     * Whether the LLM warm-up on startup feature is enabled
     * @type {boolean}
     * @memberof StatusResponse
     */
    'warmUpEnabled': boolean;
}

