/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface STTInfo
 */
export interface STTInfo {
    /**
     * Name of the speech-to-text engine being used (e.g., \'whisper.cpp\')
     * @type {string}
     * @memberof STTInfo
     */
    'engine': string;
    /**
     * Name of the specific STT model loaded (e.g., \'tiny.en\')
     * @type {string}
     * @memberof STTInfo
     */
    'model': string;
}

