/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TranscribeResponse
 */
export interface TranscribeResponse {
    /**
     * The raw transcribed text from the speech-to-text engine
     * @type {string}
     * @memberof TranscribeResponse
     */
    'transcription': string;
    /**
     * The final output text, which may be the raw transcription or its rewritten version if a prompt was provided
     * @type {string}
     * @memberof TranscribeResponse
     */
    'result': string;
}

