/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Mode } from './mode';

/**
 * 
 * @export
 * @interface TranscribeRequest
 */
export interface TranscribeRequest {
    /**
     * The user-defined trigger name (typically \'talk\') that activated speech-to-text recording
     * @type {string}
     * @memberof TranscribeRequest
     */
    'trigger': string;
    /**
     * 
     * @type {string}
     * @memberof TranscribeRequest
     */
    'prompt'?: string | null;
    /**
     * The insertion mode determining how output text should be placed (\'append\' or \'replace\')
     * @type {Mode}
     * @memberof TranscribeRequest
     */
    'mode': Mode;
    /**
     * Whether to copy the resulting transcription to the clipboard
     * @type {boolean}
     * @memberof TranscribeRequest
     */
    'clipboard'?: boolean;
    /**
     * Whether to automatically paste the result at the cursor position
     * @type {boolean}
     * @memberof TranscribeRequest
     */
    'autoPaste'?: boolean;
}



