/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { RewriteRequest } from '../models';
// @ts-ignore
import type { RewriteResponse } from '../models';
/**
 * RewriteApi - axios parameter creator
 * @export
 */
export const RewriteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Takes user text input and a prompt template, then processes it with the local LLM.                          The endpoint handles:             - Applying the prompt template to the raw input             - Processing the combined text through the local LLM (Rene)             - Returning the LLM\'s response for insertion at cursor or clipboard                          The request includes metadata about how to handle the output (append/replace, clipboard/paste).
         * @summary Process text input with a specified prompt using the local LLM
         * @param {RewriteRequest} rewriteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rewriteApiV1RewritePost: async (rewriteRequest: RewriteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rewriteRequest' is not null or undefined
            assertParamExists('rewriteApiV1RewritePost', 'rewriteRequest', rewriteRequest)
            const localVarPath = `/api/v1/rewrite/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rewriteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RewriteApi - functional programming interface
 * @export
 */
export const RewriteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RewriteApiAxiosParamCreator(configuration)
    return {
        /**
         * Takes user text input and a prompt template, then processes it with the local LLM.                          The endpoint handles:             - Applying the prompt template to the raw input             - Processing the combined text through the local LLM (Rene)             - Returning the LLM\'s response for insertion at cursor or clipboard                          The request includes metadata about how to handle the output (append/replace, clipboard/paste).
         * @summary Process text input with a specified prompt using the local LLM
         * @param {RewriteRequest} rewriteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rewriteApiV1RewritePost(rewriteRequest: RewriteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RewriteResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rewriteApiV1RewritePost(rewriteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RewriteApi.rewriteApiV1RewritePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RewriteApi - factory interface
 * @export
 */
export const RewriteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RewriteApiFp(configuration)
    return {
        /**
         * Takes user text input and a prompt template, then processes it with the local LLM.                          The endpoint handles:             - Applying the prompt template to the raw input             - Processing the combined text through the local LLM (Rene)             - Returning the LLM\'s response for insertion at cursor or clipboard                          The request includes metadata about how to handle the output (append/replace, clipboard/paste).
         * @summary Process text input with a specified prompt using the local LLM
         * @param {RewriteRequest} rewriteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rewriteApiV1RewritePost(rewriteRequest: RewriteRequest, options?: RawAxiosRequestConfig): AxiosPromise<RewriteResponse> {
            return localVarFp.rewriteApiV1RewritePost(rewriteRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RewriteApi - object-oriented interface
 * @export
 * @class RewriteApi
 * @extends {BaseAPI}
 */
export class RewriteApi extends BaseAPI {
    /**
     * Takes user text input and a prompt template, then processes it with the local LLM.                          The endpoint handles:             - Applying the prompt template to the raw input             - Processing the combined text through the local LLM (Rene)             - Returning the LLM\'s response for insertion at cursor or clipboard                          The request includes metadata about how to handle the output (append/replace, clipboard/paste).
     * @summary Process text input with a specified prompt using the local LLM
     * @param {RewriteRequest} rewriteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RewriteApi
     */
    public rewriteApiV1RewritePost(rewriteRequest: RewriteRequest, options?: RawAxiosRequestConfig) {
        return RewriteApiFp(this.configuration).rewriteApiV1RewritePost(rewriteRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

