/* tslint:disable */
/* eslint-disable */
/**
 * ContrextCue Sidecar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { TranscribeRequest } from '../models';
// @ts-ignore
import type { TranscribeResponse } from '../models';
/**
 * TranscribeApi - axios parameter creator
 * @export
 */
export const TranscribeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Records audio from the user\'s microphone and transcribes it to text using the local STT engine.                          The workflow involves:             1. Capturing audio using the system microphone             2. Processing through whisper.cpp for transcription             3. Optionally applying an LLM rewrite if a prompt is provided             4. Returning both the raw transcription and final result                          The request includes options for how to process and insert the result (append/replace, clipboard/paste).
         * @summary Transcribe audio input to text with optional rewrite
         * @param {TranscribeRequest} transcribeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transcribeEndpointApiV1TranscribePost: async (transcribeRequest: TranscribeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transcribeRequest' is not null or undefined
            assertParamExists('transcribeEndpointApiV1TranscribePost', 'transcribeRequest', transcribeRequest)
            const localVarPath = `/api/v1/transcribe/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transcribeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TranscribeApi - functional programming interface
 * @export
 */
export const TranscribeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TranscribeApiAxiosParamCreator(configuration)
    return {
        /**
         * Records audio from the user\'s microphone and transcribes it to text using the local STT engine.                          The workflow involves:             1. Capturing audio using the system microphone             2. Processing through whisper.cpp for transcription             3. Optionally applying an LLM rewrite if a prompt is provided             4. Returning both the raw transcription and final result                          The request includes options for how to process and insert the result (append/replace, clipboard/paste).
         * @summary Transcribe audio input to text with optional rewrite
         * @param {TranscribeRequest} transcribeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transcribeEndpointApiV1TranscribePost(transcribeRequest: TranscribeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TranscribeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transcribeEndpointApiV1TranscribePost(transcribeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TranscribeApi.transcribeEndpointApiV1TranscribePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TranscribeApi - factory interface
 * @export
 */
export const TranscribeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TranscribeApiFp(configuration)
    return {
        /**
         * Records audio from the user\'s microphone and transcribes it to text using the local STT engine.                          The workflow involves:             1. Capturing audio using the system microphone             2. Processing through whisper.cpp for transcription             3. Optionally applying an LLM rewrite if a prompt is provided             4. Returning both the raw transcription and final result                          The request includes options for how to process and insert the result (append/replace, clipboard/paste).
         * @summary Transcribe audio input to text with optional rewrite
         * @param {TranscribeRequest} transcribeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transcribeEndpointApiV1TranscribePost(transcribeRequest: TranscribeRequest, options?: RawAxiosRequestConfig): AxiosPromise<TranscribeResponse> {
            return localVarFp.transcribeEndpointApiV1TranscribePost(transcribeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TranscribeApi - object-oriented interface
 * @export
 * @class TranscribeApi
 * @extends {BaseAPI}
 */
export class TranscribeApi extends BaseAPI {
    /**
     * Records audio from the user\'s microphone and transcribes it to text using the local STT engine.                          The workflow involves:             1. Capturing audio using the system microphone             2. Processing through whisper.cpp for transcription             3. Optionally applying an LLM rewrite if a prompt is provided             4. Returning both the raw transcription and final result                          The request includes options for how to process and insert the result (append/replace, clipboard/paste).
     * @summary Transcribe audio input to text with optional rewrite
     * @param {TranscribeRequest} transcribeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TranscribeApi
     */
    public transcribeEndpointApiV1TranscribePost(transcribeRequest: TranscribeRequest, options?: RawAxiosRequestConfig) {
        return TranscribeApiFp(this.configuration).transcribeEndpointApiV1TranscribePost(transcribeRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

